name: frontend
description: "My talking shaha"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^17.3.0
  dio: ^5.9.2
  flutter_svg: ^2.3.0
  flutter_secure_storage: ^10.3.1
  logger: ^2.7.0
  flutter_riverpod: ^3.3.2
  image_picker: ^1.2.2
  path_provider: ^2.1.6
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_secure_storage_platform_interface: ^2.0.1
  shared_preferences_platform_interface: ^2.4.2

flutter:
  config:
    enable-swift-package-manager: true
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icons/
  - assets/icons/garage/
  - assets/icons/navigation/
  - assets/icons/events/
  - assets/icons/parts/
  - assets/icons/auth/
  
