ALTER TABLE trips  ADD COLUMN IF NOT EXISTS title VARCHAR(255);
ALTER TABLE refuel ADD COLUMN IF NOT EXISTS title VARCHAR(255);

UPDATE trips  SET title = 'Trip'   WHERE title IS NULL;
UPDATE refuel SET title = 'Refuel' WHERE title IS NULL;

ALTER TABLE trips  ALTER COLUMN title SET NOT NULL;
ALTER TABLE refuel ALTER COLUMN title SET NOT NULL;
